[package]
name = "util"
version = "0.1.0"
authors = ["zoe <zoe211@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-lite = { version = "1" }
async-io = { version = "1", optional = true }
anyhow = { version = "1", optional = true }
pin-project-lite = { version = "0", optional = true }

[features]
default = []
all = ["select", "timeout"]

select = []
timeout = ["async-io", "anyhow", "pin-project-lite"]

[dev-dependencies]
futures-lite = { version = "1" }
async-io = { version = "1"}
anyhow = { version = "1"}
pin-project-lite = { version = "0"}
util = {path=".", features=["all"]}
