[package]
name = "util"
version = "0.1.0"
authors = ["zoe <zoe211@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-core = { version = "0", optional = true }
smol = { version = "1", optional = true }

[features]
default = []
all = ["stream_vec", "timeout"]

stream_vec = ["futures-core"]
timeout = ["smol"]