[package]
name = "json_display"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
quote = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
syn = "*"